---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: key
  name: vmi-centos7-lustre-oss
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: mydisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: mydisk
    persistentVolumeClaim:
      claimName: mydisk
  - containerDisk:
      image: dlambrig/centos7-lustre:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        hostname oss
    name: cloudinitdisk
