apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mds
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /home/centos/disk

